const Colors = {
    primaryColor: '#005896',
    secondaryColor: '#FC5200',
    white: '#ffffff',
    lightGrey: '#d3d3d3',
    grey: '#f7f7f7',
    greyHeaderText: '#c0c0c0',
    textGreyColor: '#555555',
    dividerGrey: '#EEEEEE',
    black: '#333333',
    suvaGrey: '#888888',

    persianRed: '#D12F2F',
    unpaidColor: '#E8C354',
    ashColor: '#CCCCCC',
    lightYellow: '#FFF7D7',
    mayaBlue: '#69c1f1',
    eclipse: '#3a3a3a',
    lightBlue: '#198ebc',
    lightWarningRed: '#F9ECEA',
    textLightBlue: '#b3d2fc',
    lightGrayShade: '#F2F2F2',
    lightBrown: '#F49A38',
    lightYellowShade: '#efc584',
    limeColor: '#B0D657',
    ashGrey: '#efeff5',
    lightGold: '#F5A623',
    gold: '#F1C40F',
    greyShadow: '#999999',
    crayola: '#323643',
    lightRed: '#ffefef',
    gallery: '#EEEEEE',
    silver: '#BBBBBB',
    aliceBlue: '#FAFBFD',
    suluGreen: '#D1EA8C',
    warning: '#F0AD4E',
    carrotOrange: '#F47925',
    mediumGray: '#ADADAD',
    gunmetal: '#242A37',
    pureBlack: '#000000',
    icon_purple: '#9D7BD2',
    icon_green: '#A3C05F',
    textBlue: '#198EBC',
    ratingYellow: '#F7D823',
    ratingGreen: '#387C2E',
    mongoose: '#AF9E80',
    tacha: '#D4C76D',
    lightBlack: '#31394D',
    dark_grey: '#212121',
    statusBarColor: '#0E1C24',
    tabGrey: '#AAAAAA',
    lightWhite: '#EDEDF3',
    transparent: 'transparent',
    underlineColor: '#CACACA',
    yellow: '#FFFF00',
    rating_yellow: '#FFCE00',
    rating_grey: '#888888',
    gondola: '#363636',
    malachite: '#14CB53',
    middleGrey: '#777777',
    veryLightWhite: '#F5F5F5',
    WhiteSmoke: '#EAEAEA',
    darkBlack: '#000',
    viking: '#42ADBB',
    PaleOyster: '#9E8D6E',
    PurpleHeart: '#5827B7',
    neroGrey: '#252525',
    DarkOrange: '#E67D3B',
    BittersweetRed: '#FF665A',
    paleBlue: '#92e0fa',
    chipBlack: '#151515',
    chipBg: '#EFEFEF',
    violet: '#9881CD',
    bigFoodieOrange: '#ED7656',
    ToolBarPrimaryColor: '#ffffff', //toolbar color.
    primaryTextColor: '#333333', // primary text color(kinda black color) across the App,
    secondaryTextColor: '#888888', // secondary text color (grey color) for the app, like labels.
    notificationCountBgColor: '#E67D3B', // background color for notification count on toolbar.
    sideMenuBackgroundColor: '#EAEAEA', // background color of the navigation drawer.
    sideMenuHeaderBackgroundColor: '#ffffff', // background color of the navigation drawer's header.
    palegreen: '#DBDD6D', //default color of hygenic rating widget
    lightOrange: '#AF9E80',
    shadowBlack: 'rgba(0,0,0,0.7)',
    mildBlue: '#036AFF',
    mildGrey: '#CFCFCF',
    selectedItemColor: '#5D3CAD',
    yellowGreen: '#DDF29F',
    mildlightgrey: '#f8f4f4',
    basketGradientGreenStart: '#3C8730',
    tabBarActionColor: '#158DB0',
    orange: '#FFA500',
    orangeBg: '#F8F5EF',
    modifier: '#E5BA76',
    freeOption: '#FD7F06',
    offGrey: '#CCCCCC',
    express_light: '#F47925',
    express_dark: '#DE6512',
    lightGreyText: '#7d7d7d',
    mildYellow: '#AE9E80',
    rating_color: '#D82927',
    tundora: '#444444',
    tip_bg_Black: '#323334',
    mid_grey: '#9B9B9C',
    paleYellow: '#F8F5EE',
    discountColor: '#EA332F',
    lightRatingYellow: '#FFCC00',
    lightRatingGrey: '#E7E7E7',
    thinBlack: '#1E2432',
    imageBorder: '#DDDDDD',
    blackLight: '#111111',

    lightAsh: '#7A7A7A',
    cardRefund: '#D70E54',
    cardPayment: '#008CCB',

    labelGrey: '#5F6368',
    transparentWhite: '#DADCE0',
    bottomBorder: '#ECEBEB',
    rejectedColor: '#C84031',
    green: '#03fc0f',
    red: '#fc030b',
    lightGreen: '#e7ffee',
    lightWarning: '#f7e5cb',
    lightInputGrey: '#F8F8FB',
    lightBgGrey: '#F8F9FB',
    darkInputGrey: '#878DA3',
    darkInputGreyShade: '#878DA315',
    placeHolderLightGrey: '#B9C3DC',

    borderColor: '#E9E9E9',
    whiteShade: '#ffffff33',
    darkShade: '#00000033',
    blackPaymentDetails: '#414E5A',
    rowValue: '#1D1D1F',
    settingsHeader: '#F8F8FB',
    BlueHydrangea: '#B9C3DC',
    GhostWhite: '#F8F8FB',
    inputBorderColor: '#BCBFCB',
    shadowColor: '#B1B1B1',
    inactive: '#B9C3DC',

    defalutIconColor: '#414E5A',
    headerTextColor: '#1D1D1F',
    dividerColor: '#BCBFCB',
    listHeaderBackground: '#F8F8FB',
    expired: '#B9C3DC',
    headline: '#1D1D1F',
    headerBackgroundColor: '#F8F8FB',
    borderShadowColor: '#C5C5C5',
    payoutPendingColor: '#E8C354',
    avatarBackground: '#EFF3F9',
    avatarIconColor: '#005896',
    datmanColor: '#00A59B',
    withdrawButtonText: '#00A59B',
    lastPayoutSuccessColor: '#00A59B26',
    cellBorderLine: '#E8E8E9',
    iconBackgroundColor: '#DCE4F4',

    successFulChipBackground: '#dff1f1',
    failedChipBackground: '#e8e9ee',
    failChipBackground: '#f6c3bd',
    successChipText: '#00a59b',
    failChipText: '#C84031',
    FoamyMilk: '#F4EFF4',
    pendingBackground: '#DC9F371A',
    pendingText: '#DC9F37',
    inactiveButton: '#CFD2DB',
    verylightgrey: '#DEDEDE',
    darkGrey: '#F1F0F5',
    darkcyanblue: '#06304',
    paua: '#282648',
    purplePristine: '#682EA3',
    success: '#6cbf6c',
    medium_Dark_Shade_Of_Gray: '#5D5D5D',
    dark_Shade_Of_Red: '#393838'
};

export default Colors;
